dist: bionic
language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - setup=basic
  matrix:
    - laravel=^5.7
    - laravel=^5.8
    - laravel=^6.0
    - laravel=^7.0
    - setup=stable laravel=^5.7
    - setup=stable laravel=^5.8
    - setup=stable laravel=^6.0
    - setup=stable laravel=^7.0
    - setup=lowest laravel=^5.7
    - setup=lowest laravel=^5.8
    - setup=lowest laravel=^6.0
    - setup=lowest laravel=^7.0

install:
  - composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 7.1
      env: setup=basic laravel=^5.7
    - php: 7.1
      env: setup=basic laravel=^5.8
    - php: 7.1
      env: setup=stable laravel=^5.7
    - php: 7.1
      env: setup=stable laravel=^5.8
    - php: 7.1
      env: setup=lowest laravel=^5.7
    - php: 7.1
      env: setup=lowest laravel=^5.8
    - php: 7.4
      env: setup=basic laravel=^5.8
    - php: 7.4
      env: setup=basic laravel=^6.0
    - php: 7.4
      env: setup=basic laravel=^7.0
    - php: 7.4
      env: setup=stable laravel=^5.8
    - php: 7.4
      env: setup=stable laravel=^6.0
    - php: 7.4
      env: setup=stable laravel=^7.0
    - php: 7.4
      env: setup=lowest laravel=^6.0
    - php: 7.4
      env: setup=lowest laravel=^7.0
  fast_finish: true
